"""Soil configuration data."""

SOIL_TYPES = {
    "nitisol": {
        "SM0": 0.45,
        "SMFCF": 0.36,
        "SMW": 0.15,
        "CRAIRC": 0.06,
        "RDMSOL": 120.0,
        "K0": 10.0,
        "SOPE": 1.0,
        "KSUB": 1.0,
        "NSOILBASE": 60.0,
        "description": "Highland clay-loam (good)",
    },
    "andosol": {
        "SM0": 0.50,
        "SMFCF": 0.40,
        "SMW": 0.12,
        "CRAIRC": 0.05,
        "RDMSOL": 150.0,
        "K0": 20.0,
        "SOPE": 2.0,
        "KSUB": 1.5,
        "NSOILBASE": 100.0,
        "description": "Volcanic soil (excellent)",
    },
    "vertisol": {
        "SM0": 0.50,
        "SMFCF": 0.45,
        "SMW": 0.25,
        "CRAIRC": 0.04,
        "RDMSOL": 80.0,
        "K0": 2.0,
        "SOPE": 0.5,
        "KSUB": 0.3,
        "NSOILBASE": 50.0,
        "description": "Black cotton clay (wheat)",
    },
    "ferralsol": {
        "SM0": 0.42,
        "SMFCF": 0.32,
        "SMW": 0.14,
        "CRAIRC": 0.06,
        "RDMSOL": 100.0,
        "K0": 8.0,
        "SOPE": 1.0,
        "KSUB": 0.8,
        "NSOILBASE": 35.0,
        "description": "Tropical red (low N)",
    },
    "luvisol": {
        "SM0": 0.38,
        "SMFCF": 0.25,
        "SMW": 0.10,
        "CRAIRC": 0.08,
        "RDMSOL": 80.0,
        "K0": 15.0,
        "SOPE": 2.0,
        "KSUB": 1.0,
        "NSOILBASE": 25.0,
        "description": "Semi-arid sandy-loam (very low N)",
    },
}

# Soil parameter descriptions: (name, description, min_val, max_val)
SOIL_PARAM_INFO = {
    "SM0": ("Saturation", "Soil moisture at saturation (cm3/cm3)", 0.3, 0.6),
    "SMFCF": ("Field Capacity", "Soil moisture at field capacity (cm3/cm3)", 0.2, 0.5),
    "SMW": ("Wilting Point", "Soil moisture at wilting point (cm3/cm3)", 0.05, 0.3),
    "CRAIRC": ("Air Content", "Critical air content for aeration (cm3/cm3)", 0.02, 0.1),
    "RDMSOL": ("Root Depth", "Maximum rooting depth allowed (cm)", 50, 200),
    "K0": ("Hydraulic Cond.", "Saturated hydraulic conductivity (cm/day)", 1, 50),
    "SOPE": ("Percolation", "Maximum percolation rate (cm/day)", 0.1, 5),
    "KSUB": ("Subsoil Cond.", "Subsoil hydraulic conductivity (cm/day)", 0.1, 5),
    "NSOILBASE": ("Soil N Pool", "Soil nitrogen pool (kg N/ha)", 10, 150),
    "NSOILBASE_FR": (
        "N Mineralization",
        "Fraction of soil N available (fraction)",
        0.01,
        0.1,
    ),
}
